name: Distribution of release

on:
  release:
    types: [published]

jobs:
  distribution:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 8
        uses: actions/setup-java@v1
        with:
          java-version: "1.8"
          java-package: jdk+fx
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20.x"
      - name: Install Dependencies and Build Web Client
        working-directory: ./konnect-md-rp-cliweb
        run: npm install && npm run build
      - name: Setup Gradle
        uses: gradle/gradle-build-action@0d13054264b0bb894ded474f08ebb30921341cee
      - name: Build Java Service Backend
        working-directory: ./konnect-md-rp-backend
        run: ./gradlew distribute
      - name: Upload to Digital Ocean
        working-directory: ./konnect-md-rp-backend
        uses: BetaHuhn/do-spaces-action@v2
        with:
          access_key: ${{ secrets.SPACES_ACCESS_KEY }}
          secret_key: ${{ secrets.SPACES_SECRET_KEY }}
          space_name: ${{ secrets.SPACES_NAME }}
          space_region: ${{ secrets.SPACES_REGION }}
          source: output
          out_dir: Konnect
      - name: Create releases notes
        run: echo "*Konnect Mais Delivery/LeCheff - ${{ github.event.release.name}}*`n`n${{ github.event.release.body}}`n*https://kinfor.nyc3.digitaloceanspaces.com/Konnect/Konnect_MD_LeCheff_${{github.event.release.tag_name}}.exe`n" > \a\konnect-md-rp\konnect-md-rp\konnect-md-rp-backend\resources\temp\message.txt
      - name: Notify release to channels
        working-directory: ./konnect-md-rp-backend
        uses: gradle/gradle-build-action@0d13054264b0bb894ded474f08ebb30921341cee
        with:
          arguments: notificate --url=${{ secrets.NOTIFICATION_API_URL}} --token=${{ secrets.NOTIFICATION_API_TOKEN}} --userId=${{ secrets.NOTIFICATION_USER_ID}}
