name: Distribution of release

on:
  release:
    types: [published]

jobs:
  distribution:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 8
        uses: actions/setup-java@v1
        with:
          java-version: "1.8"
          java-package: jdk+fx
      - name: Build release
        uses: gradle/gradle-build-action@0d13054264b0bb894ded474f08ebb30921341cee
        with:
          arguments: distribute
      - name: Upload to Digital Ocean
        uses: BetaHuhn/do-spaces-action@v2
        with:
          access_key: ${{ secrets.SPACES_ACCESS_KEY }}
          secret_key: ${{ secrets.SPACES_SECRET_KEY }}
          space_name: ${{ secrets.SPACES_NAME }}
          space_region: ${{ secrets.SPACES_REGION }}
          source: output
          out_dir: KMessenger
      - name: Create releases notes
        run: echo "*KMessenger - ${{ github.event.release.name}}*`n`n${{ github.event.release.body}}`n*https://kinfor.nyc3.digitaloceanspaces.com/KMessenger/KMessenger_${{github.event.release.tag_name}}.exe`n" > \a\kmessenger\kmessenger\resources\temp\message.txt
      - name: Notify release to channels
        uses: gradle/gradle-build-action@0d13054264b0bb894ded474f08ebb30921341cee
        with:
          arguments: notificate --url=${{ secrets.NOTIFICATION_API_URL}} --token=${{ secrets.NOTIFICATION_API_TOKEN}} --userId=${{ secrets.NOTIFICATION_USER_ID}}
